/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\Animacia_1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Animacia_1.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty001" position={[0, 10.558, -1.994]} rotation={[Math.PI / 2, 0, 0]} />
        <group name="Armature" position={[0, 11.747, -1.024]} scale={[0.195, 0.239, 0.195]}>
          <primitive object={nodes.Bone} />
          <skinnedMesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.001']} skeleton={nodes.Cube.skeleton} />
          <skinnedMesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.Material} skeleton={nodes.Cube001.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Animacia_1.glb')
